name: Trigger auto deployment for olympicks

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/olympicks-AutoDeployTrigger-39131340-d259-48a3-8f7f-1f99c6aef2cd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Frontend
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OLYMPICKS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OLYMPICKS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OLYMPICKS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: olympicks.azurecr.io
          registryUsername: ${{ secrets.OLYMPICKS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OLYMPICKS_REGISTRY_PASSWORD }}
          containerAppName: olympicks
          resourceGroup: Olympicks
          imageToBuild: olympicks.azurecr.io/olympicks:${{ github.sha }}
          buildArguments: |
            NEON_AUTH_JWKS_URL=${{ vars.NEON_AUTH_JWKS_URL }}
            NEXT_PUBLIC_API_BASE=${{ vars.NEXT_PUBLIC_API_BASE }}
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_STACK_PROJECT_ID=${{ vars.NEXT_PUBLIC_STACK_PROJECT_ID }}
            NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=${{ vars.NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY }}
            STACK_SECRET_SERVER_KEY=${{ secrets.STACK_SECRET_SERVER_KEY }}


